<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>fastlio_tf_bridge</name>
  <version>0.1.0</version>
  <description>Bridge FAST-LIO odometry (camera_init-&gt;body) to Nav2 TF tree (map-&gt;odom-&gt;base_link)</description>
  <maintainer email="vujade17171@example.com">vujade17171</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>nav_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>geometry_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
